'use client';
import { createPagesBrowserClient} from '@supabase/auth-helpers-nextjs';

import { SessionContextProvider } from '@supabase/auth-helpers-react';
import './globals.css'
import { Inter } from 'next/font/google'
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const initialstate=()=>createPagesBrowserClient();
  const[supabaseClient]= useState(initialstate);
  return (
    <html lang="en">
      <SessionContextProvider
      supabaseClient={supabaseClient}
      initialSession={children.initialSession}
      
      >
      <body className={inter.className}>{children}</body>
      </SessionContextProvider>
    </html>
  )
}
